[project]
name = "balena-cloud"
version = "0.0.0"
description = "Asynchronous Python client to interact with the Balena Cloud API"
authors = [{ name="Klaas Schoute", email="<klaas@mrgreenoffices.nl>"}]
maintainers = [{name="Klaas Schoute", email="<klaas@mrgreenoffices.nl>"}]
license = "MIT"
requires-python = ">=3.11"
readme = "README.md"
keywords = ["balena-cloud", "api", "async", "client"]
classifiers = [
  "Framework :: AsyncIO",
  "Intended Audience :: Developers",
  "Natural Language :: English",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
dynamic = ["dependencies"]
packages = [
  { include = "balena_cloud", from = "src"},
]

[tool.poetry.dependencies]
aiohttp = "^3.13.0"
python = "^3.11"
yarl = "^1.22.0"
mashumaro = "^3.17"
orjson = "^3.11.3"

[project.urls]
homepage = "https://github.com/MrGreenBoutiqueOffices/python-balena-cloud"
repository = "https://github.com/MrGreenBoutiqueOffices/python-balena-cloud"
documentation = "https://github.com/MrGreenBoutiqueOffices/python-balena-cloud"
"Bug Tracker" = "https://github.com/MrGreenBoutiqueOffices/python-balena-cloud/issues"
Changelog = "https://github.com/MrGreenBoutiqueOffices/python-balena-cloud/releases"

[tool.poetry.group.dev.dependencies]
aresponses = "3.0.0"
codespell = "2.4.1"
covdefaults = "2.3.0"
coverage = {version = "7.13.4", extras = ["toml"]}
pre-commit-hooks = "6.0.0"
prek = "0.3.3"
pylint = "4.0.5"
pytest = "9.0.2"
pytest-asyncio = "1.3.0"
pytest-cov = "7.0.0"
ruff = "0.15.4"
syrupy = "5.1.0"
ty = "0.0.19"
yamllint = "1.38.0"

[tool.coverage.run]
plugins = ["covdefaults"]
source = ["balena_cloud"]

[tool.coverage.report]
fail_under = 90
show_missing = true

[tool.pylint.MASTER]
ignore = ["tests"]

[tool.pylint.BASIC]
good-names = ["_", "ex", "fp", "i", "id", "j", "k", "on", "Run", "T"]

[tool.pylint."MESSAGES CONTROL"]
disable= [
  "duplicate-code",
  "format",
  "unsubscriptable-object",
]

[tool.pylint.SIMILARITIES]
ignore-imports = true

[tool.pylint.FORMAT]
max-line-length = 88

[tool.pylint.DESIGN]
max-attributes = 20

[tool.pytest.ini_options]
addopts = "--cov"
asyncio_mode = "auto"

[tool.ruff]
lint.select = ["ALL"]
lint.ignore = [
  "ANN401",  # Opinioated warning on disallowing dynamically typed expressions
  "D203",    # Conflicts with other rules
  "D213",    # Conflicts with other rules
  "D417",    # False positives in some occasions
  "PLR2004", # Just annoying, not really useful
  "SLOT000", # Has a bug with enums: https://github.com/astral-sh/ruff/issues/5748

  # Conflicts with the Ruff formatter
  "COM812",
]

[tool.ruff.lint.flake8-pytest-style]
mark-parentheses = false
fixture-parentheses = false

[tool.ruff.lint.isort]
known-first-party = ["balena_cloud"]

[tool.ruff.lint.mccabe]
max-complexity = 25

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
